config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace "admin" do
    resources :jobs do
      post :close, on: :member
    end
  end

  resources :jobs do
    post "viewed", on: :member
    get "manage", on: :member
  end

  resources :job_post_requests, only: [:new, :create]
  resource :sitemap, only: :show

  get 'about' => 'site#about'
  get 'job_post_request' => 'job_post_requests#new'
  get "calendar", to: "site#calendar"

  get 'code-of-conduct' => 'site#coc'

  get 'hackies' => 'site#hackies'

  get '/newsletter/subscribe' => redirect('https://buttondown.email/indyhackers')
  get '/newsletter' => 'newsletters#index'
  get '/newsletter/archive' => 'newsletters#archive'

  get '/events' => 'events#index'
  get '/sponsors' => 'sponsors#index'

  resources :redirects, only: [:show], constraints: { id: /[a-z0-9_]+/i }, path: "r"

  get 'coc' => 'site#coc'

  root to: "site#index"
end

app/models/job.rb
class Job < ActiveRecord::Base
  is_sluggable :name

  has_many :job_views, dependent: :destroy
  has_many :viewers, through: :job_views
  belongs_to :user, optional: true

  attr_accessor :publish_now

  after_create :notify_created
  after_update :notify_if_published

  class << self
    def active
      published
        .where("jobs.published_at >= :date", date: 60.days.ago)
        .where("expires_at IS NULL OR expires_at >= :date", date: Time.zone.now)
    end

    def expired
      published
        .where("jobs.published_at < :date", date: 60.days.ago)
        .or(published.where("expires_at IS NOT NULL AND expires_at < :date", date: Time.zone.now))
    end

    def unpublished
      where(published_at: nil)
    end

    def from_job_post_request(job_post_request)
      Job.new(
        title: job_post_request.title,
        description: job_post_request.description,
        company: job_post_request.company,
        salary: job_post_request.salary
      )
    end

    private

    def published
      where.not(published_at: nil)
           .where("published_at <= :date", date: Time.zone.now)
    end
  end

  def name
    "#{title} at #{company}"
  end

  # The 'slugged' gem expects this method to exist, as it's expecting the
  # method to be an AR attribute.
  def name_changed?
    will_save_change_to_title? || will_save_change_to_company?
  end

  # Compatibility method for slugged gem due to current Rails changes to the "ActiveModel::Dirty" methods
  def slug_was
    slug_before_last_save
  end

  # Compatibility method for slugged gem due to current Rails changes to the "ActiveModel::Dirty" methods
  def cached_slug_was
    cached_slug_before_last_save
  end

  # Compatibility method for slugged gem due to current Rails changes to the "ActiveModel::Dirty" methods
  def slug_changed?
    saved_change_to_slug?
  end

  # Compatibility method for slugged gem due to current Rails changes to the "ActiveModel::Dirty" methods
  def cached_slug_changed?
    saved_change_to_cached_slug?
  end

  def notify_created
    return if ENV["SLACK_WEBSITE_COMMITTEE_WEBHOOK"].blank?

    url = "https://www.indyhackers.org/admin/jobs"
    message = "New job board submission: <#{url}|#{title} at #{company}>"

    HTTParty.post(
      ENV["SLACK_WEBSITE_COMMITTEE_WEBHOOK"],
      body: {
        text: message
      }.to_json,
      headers: { "Content-Type" => "application/json" }
    )
  end

  def notify_if_published
    return unless recently_published?

    SystemMailer.job_post_published(user, self).deliver_now
  end

  def increment_views
    self.views = views.nil? ? 1 : views + 1
  end

  private

  def recently_published?
    saved_change_to_published_at? && published_at.present? && published_at <= Time.now
  end
end

app/models/job_view.rb
class JobView < ActiveRecord::Base
  belongs_to :job
  belongs_to :viewer
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_admin!
  before_action :fetch_job, only: %i[show edit update close destroy]
  skip_before_action :verify_authenticity_token, only: %i[close destroy]

  def index
    @jobs = Job.order(created_at: :desc)

    params[:job_view] ||= "all"
    case params[:job_view]
    when "active"
      @jobs = @jobs.active
    when "expired"
      @jobs = @jobs.expired
    when "unpublished"
      @jobs = @jobs.unpublished
    end

    @jobs = @jobs.page(params[:page])
  end

  def show; end

  def new
    @job = Job.new
  end

  def edit; end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_job_path(@job), notice: "Job was successfully created."
    else
      render :new
    end
  end

  def update
    if @job.update(job_params)
      redirect_to job_path(@job), notice: "Job was updated successfully"
    else
      render :edit
    end
  end

  def close
    @job.update(expires_at: Time.zone.now)
    redirect_to admin_jobs_path, notice: "Job was successfully closed."
  end

  def destroy
    @job.destroy
    redirect_to admin_jobs_path, notice: "Job was successfully destroyed."
  end

  private

  def fetch_job
    @job = Job.find_using_slug(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :company, :salary, :published_at)
  end
end

app/controllers/jobs_controller.rb
require "digest/md5"
class JobsController < ApplicationController
  before_action :authenticate_by_token, only: %i[edit destroy]

  def index
    @jobs = Job.active.order("created_at DESC")
    respond_to do |format|
      format.html
      format.atom { render layout: false }
      format.rss { redirect_to jobs_path(format: :atom), status: :moved_permanently }
    end
  end

  def show
    if find_job.blank?
      redirect_to(jobs_path, notice: "Couldn't find that job. It may have been filled. Sorry!") and return
    end

    increment_job_views!
  end

  def edit
    return if find_job.present?

    redirect_to(jobs_path, notice: "Couldn't find that job.")
  end

  def update
    if find_job.blank?
      redirect_to(jobs_path, notice: "Couldn't find that job.")
    elsif @job.update(job_params)
      redirect_to(edit_job_path(@job, token: params[:token]), notice: "Your job post was updated")
    else
      render :edit
    end
  end

  def destroy
    if find_job.blank?
      redirect_to(jobs_path, notice: "Couldn't find that job.")
    else
      @job.update(expires_at: Time.zone.now)
      redirect_to jobs_path, notice: "Job post closed. Thanks!"
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :company, :published_at)
  end

  def authenticate_by_token
    find_job
    return nil if @job.blank?

    @user = User.find_by_token(params[:token]) unless params[:token].nil?
    return if @user.present? && @job.user == @user

    redirect_to jobs_url, notice: "*gasp* You shouldn't be snooping around there! FOR SHAME!"
  end

  def find_job
    @job = Job.active.find_using_slug(params[:id])
  end

  def increment_job_views!
    set_cookie_ih_id!
    viewer = viewer_from_cookie

    return if viewer.viewed?(@job)

    @job.viewers << viewer
    @job.increment_views
    @job.save
  end

  def set_cookie_ih_id!
    cookies["_ih_uid"] = Digest::MD5.hexdigest(Time.now.to_s + rand(13_000).to_s) if cookies["_ih_uid"].nil?
  end

  def viewer_from_cookie
    Viewer.find_or_create_by!(client_hash: cookies["_ih_uid"])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_view_links
    %w[all unpublished active expired].map do |filter_type|
      label = "#{filter_type.titleize} Jobs"
      if params[:job_view] == filter_type
        tag.span label
      else
        link_to label, admin_jobs_path(page: params[:page], job_view: filter_type)
      end
    end.join(" | ").html_safe
  end
end

app/views/admin/jobs/edit.html.haml
- content_for :footer do
  = javascript_include_tag 'showdown'

.readable.container
  = simple_form_for @job, :url => admin_job_path(@job), :html => {:multipart => true} do |f|
    %fieldset
      %legend Edit Job
      = f.input :title
      = f.input :company
      = f.input :salary, label: "Salary range"
      = f.input :description
      = f.input :published_at, :as => :date
      .if-no-contact
        = "If they didn't leave a way to apply, append this to the bottom: \"To apply, please contact [#{@job.try(:user).try(:name)}](mailto:#{@job.try(:user).try(:email)})"
      .input
        %label &nbsp;
        = f.button :submit, 'Save'

.job.readable.container
  %h2 Preview
  %h1= @job.title || "&nbsp;"
  .job-description#markdown-target
    = MARKDOWN.render(@job.description).html_safe

app/views/admin/jobs/index.html.haml
.container
  %h2 Jobs

  #job-view-filter= job_view_links
  %p= link_to 'Create a New Job', new_admin_job_path, class: 'button-black'
  %table#jobs
    %tr
      %th Name
      %th Requested
      %th Published
      %th Expires
      %th Views
      %th Actions
    - @jobs.each do |job|
      %tr
        %td= job.name
        %td.requested= l(job.created_at, format: :murican)
        %td.published= l(job.published_at, format: :murican) unless job.published_at.nil?
        %td.expires= l(job.expires_at, format: :murican) unless job.expires_at.nil?
        %td.views= job.views || 0
        %td.actions
          = link_to 'edit', edit_admin_job_path(job), title: 'edit'
          |
          = link_to 'close', close_admin_job_path(job), method: :post, title: 'close', confirm: 'Are you sure you wanna close this job?'
          |
          = link_to 'delete', admin_job_path(job), method: :delete, title: 'delete', confirm: 'Are you sure you wanna destroy this job?'
  = paginate(@jobs)

app/views/admin/jobs/new.html.haml
%li.readable
  = simple_form_for @job, :url => admin_jobs_path do |f|
    %fieldset
      %legend New Job
      = f.input :title
      = f.input :company
      = f.input :description
      .input
        %label &nbsp;
        = f.button :submit, 'Save'

app/views/admin/jobs/show.html.haml
%section.job.container#single-job
  %h1= @job.name
  %article.job-description
    = MARKDOWN.render(@job.description).html_safe