config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace "admin" do
    resources :jobs do
      post :close, on: :member
    end
  end

  resources :jobs do
    post "viewed", on: :member
    get "manage", on: :member
  end

  resources :job_post_requests, only: [:new, :create]
  resource :sitemap, only: :show

  get 'about' => 'site#about'
  get 'job_post_request' => 'job_post_requests#new'
  get "calendar", to: "site#calendar"

  get 'code-of-conduct' => 'site#coc'

  get 'hackies' => 'site#hackies'

  get '/newsletter/subscribe' => redirect('https://buttondown.email/indyhackers')
  get '/newsletter' => 'newsletters#index'
  get '/newsletter/archive' => 'newsletters#archive'

  get '/events' => 'events#index'
  get '/sponsors' => 'sponsors#index'

  resources :redirects, only: [:show], constraints: { id: /[a-z0-9_]+/i }, path: "r"

  get 'coc' => 'site#coc'

  root to: "site#index"
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}/

    %title= yield(:title).blank? ? "IndyHackers - Events and Jobs for Tech Folks in Indianapolis" : "#{yield(:title)} - IndyHackers"

    %meta{:content => 'IndyHackers', :name => "author"}/
    - if yield(:description).blank?
      %meta{:content => "Bringing together hackers in Indiana", :name => "Description"}/
    - else
      = yield(:description)
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Work+Sans&display=swap" rel="stylesheet">

    = stylesheet_link_tag 'application'
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    = favicon_link_tag "/favicon.png"
    = yield(:head)

  %body{class: "#{params[:controller].split('/').join(' ')} #{params[:action]}"}
    = admin_header
    .main.main-body.container
      .header.navbar
        %div.logo-container.navleft
          = link_to image_tag('ih-logo-black.png', alt: 'Indy Hackers Logo', width: '300px'), "/"

        %ul.menu.navright
          %li= link_to 'Home', '/'
          %li= link_to 'Newsletter', '/newsletter'
          %li= link_to 'Jobs', '/jobs'
          %li= link_to 'Events', '/events'
          %li= link_to 'Sponsors', '/sponsors'
          %li= link_to 'About', '/about'

      .content.clear-fix
        - if notice
          %section
            .notice= notice
        - if alert
          %section
            .alert.danger= alert
        = yield

      .footer
        %div.footer-links
          %div
            %span About Us
            %p
              =link_to 'Meet our Board', '/about'
            %p
              =link_to 'Code of Conduct', '/coc'
            // %p
            //  =link_to 'Mentorship Program', '/'
            %p
              =link_to 'Donate', 'https://donate.stripe.com/bIY17XcYL77c0HSdQQ', target: :_blank

          %div
            %span Contact
            %p
              = link_to '@indyhackersorg', "https://twitter.com/indyhackersorg"
            %p
              = link_to 'Slack Community', "https://slack.indyhackers.org"
            %p
              = link_to 'GitHub', "https://github.com/indyhackers/indyhackers.org"
        %div.made-by
          = link_to inline_svg_tag('ih-logo.svg', :class => 'logo-gray'), '/'
          %p.ff-sm
            Made with ❤️ by the Indy Hackers board

    = javascript_include_tag 'application'
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZF5Q1C13NM"></script>
    :javascript
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-ZF5Q1C13NM');
    = yield(:footer)

app/views/layouts/wide.html.haml
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}/
    %title IndyHackers
    %meta{:content => 'Miles Z. Sterrett', :name => "author"}/
    %meta{:content => "Bringing together hackers in the Indianapolis area.", :name => "Description"}/
    %link{:href => "/jobs.xml", :rel => "alternate", :title => "Job Board Feed", :type => "application/atom+xml"}/
    %link{:href => "//fonts.googleapis.com/css?family=Philosopher&subset=latin", :rel => "stylesheet", :type => "text/css"}/
    / 960 Grid System
    = stylesheet_link_tag '960/reset', '960/text', '960/960', 'screen'
  %body
    #header
      #menu-container.container_12
        %h1
          %a{:href => "/"} IndyHackers
        %ul#menu
          - if admin_signed_in?
            %li= link_to 'jobs admin', admin_jobs_path
            %li= link_to 'logout', destroy_admin_session_path
            %li ||
          %li
            %a{:href => "/jobs"} jobs
          %li
            %a{:href => "/job_post_requests/new"} submit a job
          %li.last
            %a{:href => "http://blog.indyhackers.org"} blog
    .container_12
      #body
        .grid_12
          - if notice
            %div.notice= notice
          - if alert
            %div.alert= alert
          = yield
        .clear &nbsp;
      #footer
        %hr/
        .grid_6.prefix_3.suffix_3
          :markdown
            Made with love by [mileszs](https://mileszs.com) :: Follow us [on Twitter](https://twitter.com/indyhackersorg)

        .clear &nbsp;
    <!-- Google Analytics -->
    :javascript
      var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
      document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    :javascript
      try {
        var pageTracker = _gat._getTracker("UA-3615572-3");
        pageTracker._trackPageview();
        } catch(err) {}
    <!-- END Google Analytics -->
    = yield(:footer)
    = javascript_include_tag 'jquery-1.5.min', 'rails', 'app'